### ISSUE TITLE
Some Legitimate Videos Blocked

### ISSUE THREAD

**Issue by ashleycawley** [kboghdady/youTube_ads_4_pi-hole#57]
After implementing the blacklists I'm seeing some legitimate videos being blocked, the YouTube videos simply wont begin playing, witnessed on both a Roku TV Stick and on a Win7 Desktop. Most videos play fine but some do not.

I'm in the UK if that is of any relevance.

**Comment by RobinFrcd** [comment]
Same here on firefox/chrome on MacOS. 

3 entries were blocked:

- `r2---sn-hp57yn7r.googlevideo.com`
- `r3---sn-4g5e6nsz.googlevideo.com`
- `r3---sn-25ge7nse.googlevideo.com`

I guess one of them is used to serve the video itself

**Comment by one800J** [comment]
Understatement of the year. Blocked every youtube video. Was up all night, last 12 hours trying to figure it out. You can't. They reuse addresses for videos and if one if blocked it will just try and try again using a new number.  Now I'm going to just completely wipe my pi hole and start over.  Ad Block in firefox has had YouTube ad blocking down for years.  No idea how they do it.  Every other browser can't. 

And if you wanna know specs… this was on 2 iPhones, a LGwebOS TV, AppleTV, and 2 mac workstations.  What a mess.  You'd have to make some script like ab block uses and have it run on the side somewhere.  

I vote every video I watch with an ad thumbs down.    $12 a month gets you no ads.  

I mean I had settings for the last week that were pretty good blocking 98% of YT ads then they changed something again.  dicks.

**Comment by ashleycawley** [comment]
@one800J thats a really sucky thing to do - don’t thumbs down videos just because you don’t like ads, stop using YouTube if you find it that abhorrent. Some content creators don’t even have the decision whether an Ad is shown on their video or not sometimes Google just makes that decision for them & pockets the money them-self (I speak from experience there). That sucks for the content creator who might want to give you the vid ad-free, but ontop of that sucky Google move they have to put up with they also got you; selectively picking out what you want to watch, some content creator has spent hours making, you consume it and then rate down their work just because you encountered an ad they may or may-not have had a decision in being displayed. Its disrespectful to the content creators & childishly self-centered, grow up.

**Comment by one800J** [comment]
👎. First off yeah ah they do. They choose to monotone or not. Heck even as breaks. How many ads. Can the user skip the ad. If they don’t make any money from it it’s only because they used someone else’s copy written material in it like a song.  And I am a film/TV editor. I’ve worked years on projects only to have people crap all over them. It’s part of the biz. Grow a pair. There are many other ways audiences can support a channel they actually like. Patreon, onlyfans (hah), ah hell I’ve even thrown $100 to a creator during a live chat once. Mostly because they didn’t spam their videos with ads. They actually make most of their money from amazon referral sales. You don’t want to piss off your audience. You’re going to do that by forcing them to watch an ad they probably don’t care anything about that they’ve seen already 20 times today. Yesterday morning when trying to modify these dns lists, I watched I kid you not the same ad 50+ times in a row. And I forget what it was.  Lol. Really effective.  In fact I let the ad run while looking through logs.  So really I was letting it run. See that’s a creator I like. BigCLivedotcom   Creators I like ill just set up virtual machines and stream their channel 24/7 x10 letting all the ads play in full.   

So shove it. Is what I meant to say.     Btw still in the process of complexly redoing my pi.  Couldn’t get rid of these dns lists. 22,000 of them.  🤦‍♂️

**Comment by yotam-nots** [comment]
@one800J 
```
sudo sqlite3 /etc/pihole/gravity.db "delete from domainlist where domain like '%nboz.google%'"
sudo sqlite3 /etc/pihole/gravity.db "delete from domainlist where domain like '%googlevideo%'"
/usr/local/bin/pihole restartdns reload-lists >/dev/null
```

**Comment by ashleycawley** [comment]
> First off yeah ah they do. They choose to monetize or not.

I stopped reading from that point on, you obviously don't comprehend the full scope of what can happen on the YouTube ecosystem. As I said in my prior comment I speak from experience. I was a successful content-creator on YT (for a hobby) before Ad's were even a thing on YT and before HD cameras. I had 40K subscribers, when Ads came to YT, I purposely choose not to display Ads on any of my videos just for the convienience of my viewers even though I knew I could make money if I wanted to.

Years went by with my videos being Ad-free, then one day YouTube does audio content-matches on some music used in the videos (despite me having previously sought the permission of the band to use the music) and Google/YT slapped Ads on many of my videos, without my permission and without a penny coming my way. So its a crap situation for all.

**Comment by SoftwareRat** [comment]
> @one800J thats a really sucky thing to do - don’t thumbs down videos just because you don’t like ads, stop using YouTube if you find it that abhorrent. Some content creators don’t even have the decision whether an Ad is shown on their video or not sometimes Google just makes that decision for them & pockets the money them-self (I speak from experience there). That sucks for the content creator who might want to give you the vid ad-free, but ontop of that sucky Google move they have to put up with they also got you; selectively picking out what you want to watch, some content creator has spent hours making, you consume it and then rate down their work just because you encountered an ad they may or may-not have had a decision in being displayed. Its disrespectful to the content creators & childishly self-centered, grow up.

i dont give a fuck about them. They earn too much money just for playing some games or talking.
