### ISSUE TITLE
Doesn't block YT ads

### ISSUE THREAD

**Issue by rednag** [kboghdady/youTube_ads_4_pi-hole#93]
Hi,

I've added the block list, but I'm still having ads during YT videos especially at the start of the video. What's the matter? Is it not possible to block YT ads?

Thank you

**Comment by onemillionbucks** [comment]
I explained why this is the case today [Feb 3 2021 Issue report]( https://github.com/kboghdady/youTube_ads_4_pi-hole/issues/94)
It's because the queries are hashed (randomized) between videos and ads, so trying to block anything that "looks" like an ad also blacklists the video hashes. So you'll be stuck, not seeing an ad, and not seeing your video play.
